import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import { Loader2Icon } from "lucide-react";
import { Navbar1 } from "@/components/navbar1";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      
      
      <body>
        <Navbar1/>
        <TRPCReactProvider>
          <Suspense fallback=<Loader2Icon className="m-0 animate-spin" />>
            {children}
          </Suspense>
        </TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
