// Layout principal de la aplicación. Configura los proveedores globales y la estructura base.
import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import { Loader } from "lucide-react";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { CartProvider } from "@/contexts/CartContext";
import { SessionProvider } from "next-auth/react";
import ShoppingCart from "@/components/shoppingCart";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // Renderiza el layout principal con todos los proveedores y la estructura base
  return (
    <html suppressHydrationWarning lang="en" className={`${geist.variable}`}>
      <head>
        {/* Script para manejar el modo oscuro desde localStorage */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
              try {
                const dark = localStorage.getItem('darkMode') === '1';
                document.documentElement.classList.toggle('dark', dark);
              } catch (_) {}
            })()`,
          }}
        />
      </head>
      <body className="flex min-h-screen flex-col antialiased">
        <TRPCReactProvider>
          <SessionProvider>
            <CartProvider>
              {/* <NavbarClient /> */}
              <NuqsAdapter>
                <Suspense
                  fallback=<Loader className="absolute top-1/2 left-1/2 -translate-1/2 scale-150 animate-spin" />
                >
                  {children}
                  {/* Carrito de compras flotante */}
                  <div className="fixed right-8 bottom-8 z-40">
                    <ShoppingCart />
                  </div>
                </Suspense>
              </NuqsAdapter>
            </CartProvider>
          </SessionProvider>
        </TRPCReactProvider>
        {/* Toaster para notificaciones globales */}
        <Toaster />
      </body>
    </html>
  );
}
