import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { Toaster } from "@/components/ui/sonner";
import { Suspense } from "react";
import { Loader } from "lucide-react";
import { Navbar1 } from "@/components/navbar1";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { CartProvider } from "@/contexts/CartContext";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html suppressHydrationWarning lang="en" className={`${geist.variable}`}>
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `(() => {
              try {
                const dark = localStorage.getItem('darkMode') === '1';
                document.documentElement.classList.toggle('dark', dark);
              } catch (_) {}
            })()`,
          }}
        />
      </head>
      <body className="min-h-dvh">
        <TRPCReactProvider>
          <CartProvider>
            <Navbar1 />
            <NuqsAdapter>
              <Suspense
                fallback=<Loader className="absolute top-1/2 left-1/2 -translate-1/2 scale-150 animate-spin" />
              >
                {children}
              </Suspense>
            </NuqsAdapter>
          </CartProvider>
        </TRPCReactProvider>
        <Toaster />
      </body>
    </html>
  );
}
